### ISSUE TITLE
Can't Logout

### ISSUE THREAD

**Issue by super3** [Storj/metadisk-client#24]
### Package Versions

Replace the values below using the output from `npm list -g storj`.

```
└─┬ storj-bridge-client@0.4.3
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v5.1.0
```
### Expected Behavior

Should fail on login, but it should log the user out. 

```
$ storjcli login
 [error]  This device is already paired.

$ storjcli logout
 Actually logs out.
```
### Actual Behavior

Can't login because its paired. And can't logout because it tries to remove the keypair from the server.

```
$ storjcli login
 [error]  This device is already paired.

$ storjcli logout
 [error]  Public key not registered
```
### Steps to Reproduce

I could fix this by removing the configuration, but this occurs in many cases. If the public key is not registered on logout than it should locally unpair.
1. Happens whenever when the db is dumped, and all the credentials become invalid. 
2. Using staging servers, other than production. 
3. Whenever that pub key is removed from the account.

**Comment by 161chihuahuas** [comment]
Workaround for now:

```
rm .storjcli/id_ecdsa
```

**Comment by super3** [comment]
@gordonwritescode Indeed, just making sure its in the backlog somewhere.
