### ISSUE TITLE
Tempfiles are not deleted

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/metadisk-client#27]
### Package Versions

Replace the values below using the output from `npm list -g storj`.

```
└─┬ storj-bridge-client@0.4.3
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```
### Expected Behavior

Tempfiles which are created while uploading a file with `storjcli uploadfile 5734155b643156b811xxxxxx /tmp/upload/upload67.txt -k xxxxxxx` should deleted after they uploaded.
### Actual Behavior

Tempfile are not deleted after upload has finished.

```
duck@vlan2-farmer:/tmp$ storjcli uploadfile 5734155b643156b811923154 /tmp/upload/upload67.txt -k 07i6tfED3qNSu7
 [info]   Generating encryption key...
 [info]   Encrypting file "/tmp/upload/upload67.txt"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [info]   Encryption key saved to keyring.
 [info]   File successfully stored in bucket.
 [info]   Name: upload67.txt, Type: text/plain, Size: 8388624 bytes, ID: 5745f7c04294714908887620
duck@vlan2-farmer:/tmp$ ll
insgesamt 16520
drwxrwxrwt 11 root    root      65536 Mai 25 21:05 ./
drwxr-xr-x 24 root    root       4096 Mai 25 10:29 ../
-rw-rw-r--  1 duck    duck    8388608 Mai 25 21:05 7c36b514ab55
-rw-rw-r--  1 duck    duck         16 Mai 25 21:05 cdb2f76b7e2e
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Upload a file with storjcli
2. look at your tempdir `/tmp`

**Comment by 161chihuahuas** [comment]
The reason we use the operating system's tmpdir, is so that we don't need to worry about deleting the shards, instead letting the operating system handle cleaning up.

**Comment by BlackDuck888** [comment]
This is only done by a reboot, if i upload many files and don't reboot for an longer time i fill the disk an other things stop working. I do not reboot very often, and the volume were my /tmp is mounted is not very large. If the things are done the there is no reason to keep them. Windows does never a cleanup of its tempdir by itself!

**Comment by 161chihuahuas** [comment]
Oh windows... -.- Okay, will do.
