### ISSUE TITLE
Add Keyringpassphrase Command

### ISSUE THREAD

**Issue by super3** [Storj/metadisk-client#34]
### Actual Behavior

Currently the user has to enter in the passphrase every single time they want to upload a file. 

```
$ storjcli uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ******
$ storjcli uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ******
$ storjcli uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ******
```
### Expected Behavior

User is able to unlock their keyring for x number of seconds [like Bitcoin](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list). Good compromise between security and user experience. 

```
$ storjcli keyringpassphrase <passphrase> <timeout in seconds>
$ storjcli uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
$ storjcli uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
$ storjcli uploadfile 573b4ce25da55fc8715b4c5a cat.jpg
```

**Comment by super3** [comment]
Moved to https://github.com/Storj/core/issues/147

**Comment by BlackDuck888** [comment]
`$ storjcli uploadfile 5734155b643156b811923154 /tmp/upload/upload1.txt -k password` is already working to.
