### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by FDCanadaLLC** [Storj/metadisk-client#35]
### Package Versions

Replace the values below using the output from `npm list -g storj`.

```
└─┬ storj-bridge-client@0.5.2
  └── storj@1.0.2
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```
### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I use the client to upload file to my bucket. This work with a file < 1 MB, but I receive this error with a file of 180 MB : 502 Bad Gateway.

Command :

Work (< 1MB)
storjcli uploadfile 5753488e678888e642f94584 /tmp/storjtmp/photo.jpg 

Not work (180MB) : 502 Bad Gateway
storjcli uploadfile 5753488e678888e642f94584 /tmp/storjtmp/video.avi 

```
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When i run the command, this log appear in somes seconds :

 [...]  > Enter your passphrase to unlock your keyring  >  ******************************

 [info]   Generating encryption key...
 [info]   Encrypting file "/tmp/storjtmp/video.avi"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!


After I wait 7-8 minutes to receive this error :

 [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Run storjcli uploadfile 5753488e678888e642f94584 /tmp/storjtmp/video.avi 
2. Wait 7-8 minutes at this message : [info]   Storing file, hang tight!
3. Reveice the error

I can send you my SSH access to my CentOS test server.

**Comment by FDCanadaLLC** [comment]
Sorry if I'm not at the right place, the support team give me this link.
https://storj.readme.io/v1.0/discuss/57548dbe4796070e00868907

**Comment by super3** [comment]
@FDCanadaLLC You are in the right place. We will investigate.

**Comment by super3** [comment]
@FDCanadaLLC We believe this is being caused at the API level. Your 180 MB file is being broken into 8 MB pieces, so 23 pieces total. This is an intermittent error so with a small file it will be fine, but with a larger one its increasing likely to occur. We are going to be rolling out an update in the next 2-3 days to that should solve that issue.

On the other side, the client side library doesn't catch some upload errors (and its something that should happen). So if you are upload that 180 MB file, and piece 13 of 23 piece failed, then the upload would fail. Instead it should just try piece 13 again. @bookchin Do you agree that this is the case?

**Comment by 161chihuahuas** [comment]
Yes, the client should be improved to handle those scenarios: https://github.com/Storj/core/issues/146

**Comment by FDCanadaLLC** [comment]
Ok, thank you, do not hesitate if you want to test with my test server.

**Comment by 161chihuahuas** [comment]
Closing this since the bridge updates should resolve a lot of this and we have another issue open for robustness in the client.
