### ISSUE TITLE
Error messages when storing files on metadisk

### ISSUE THREAD

**Issue by webshots1** [Storj/metadisk-client#5]
Getting error messages on api.metadisk.org when trying to push a file to the bucket:

{"error":"ENOENT: no such file or directory, scandir '/root/.storjnode/shards/770c66d090fc2ebfd299d1db72b83bc540bcbb9e/challenges'"}

and

{"error":"Shard data not found"}

You should be able to reproduce the error by trying to save data here:
http://mycoinads.com/STORJnotepadDEMO/

Here is a preview of the request:

PUT /buckets/56e02f13d6185bf403ba7843/files HTTP/1.1
Host: api.metadisk.org
Connection: keep-alive
Content-Length: 369
Pragma: no-cache
Cache-Control: no-cache
Origin: http://mycoinads.com
x-token: f28cec4952af59d129e141f6e292c4d16ebe93a05fbd8e7f86ace0d4158e5346
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
x-filesize: 128
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryhP7NrPdTNiWqqRPF
Accept: application/json, text/javascript, _/_; q=0.01
Referer: http://mycoinads.com/STORJnotepadDEMO/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

------WebKitFormBoundaryhP7NrPdTNiWqqRPF
Content-Disposition: form-data; name="file"; filename="e2141e7e79464e49e2d6aa43a223bba6e6a51d2ed17ca78937ef6ec09b3cb419.txt"
Content-Type: text/html

------WebKitFormBoundaryhP7NrPdTNiWqqRPF--

**Comment by 161chihuahuas** [comment]
This is a bug at the API layer - tracking here: https://github.com/Storj/metadisk-api/issues/28
