### ISSUE TITLE
Client.prototype.resolveFileFromPointers: Uncaught TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by GalumphingCallooh** [Storj/metadisk-client#6]
Client.prototype.resolveFileFromPointers @ line# 252 in BinaryClient.send method, passes the data argument as null, which is written to the stream if NodeJS context is detected, but will throw an "Uncaught TypeError: Cannot read property 'constructor' of null" error otherwise (in the browser). This may be considered an error in BinaryJS, though.

**Comment by 161chihuahuas** [comment]
This should become resolved upon completion of https://github.com/Storj/node-storj/issues/30
